### PR TITLE
Improved use of OPTIONS dict

### PR DESCRIPTION
**Pull request by slacker-by-design**
* Making OPTIONS global within the module allows its use in both ask_choice and display_options functions
* Renaming to _OPTIONS indicates that this variable is an internal (private) feature of the user_interface module and should not be used outside of it

### CODE REVIEW

**Comment by frostphex** [comment]
first, *_, last = _OPTIONS.keys()
This line is amazing, haha. If I'm correct, here we are storing number 1 to 6 which the _OPTIONS.keys() return.

Now, the variable first = 1, and last = 6, and what is this syntax *_? It stores number 2 to 5, but never seen it anywhere before.

Is it like *args used in the functions?  I thought *args is meant to be used only in functions to collect variables and **args is used to collect name-value pairs for dictionary data.

**Comment by slacker-by-design** [comment]
Yes, your view of the mechanics is correct. The `*` is called spread (or unpacking) operator. What it does in this context is it "absorbs" the rest of the items from `_OPTIONS.keys()` into one variable, which is named `_`. The `_` is completely valid variable name that is used in contexts when you actually don't care what will it refer to, as you don't intend to use it.

You could have as well written
`first, *middle, last = _OPTIONS.keys()`
The `middle `would contain `[2, 3, 4, 5]`.

Of course, this construct is bit of a "show off". It's perfectly OK to use other approach, such as
`keys = tuple( _OPTIONS.keys())`
and then just use `keys[0]` and `keys[-1]` instead of `first` and `last` variables.

**Comment by frostphex** [comment]
Okay gotcha, so I had idea about spread operator but from JS (`...variableName`), and didn't know Python had a similar concept. 

As for the `_` this is something interesting, so one can use `_` when there is no use of that variable, like in a plain for loop which just loops over a given range? 
```
for _ in range(5):
  pass
```
I can use *middle as it now contains a list of numbers and will look decent, but when I'm not in a need of those list of numbers, I should use `_` a plain underscore?

**Comment by slacker-by-design** [comment]
Yes, the `...` in JavaScript works in a similar way. 

And yes, that would be a common use of underscore. The `_` is also often used in `match / case` as the default/fallback option (i.e. there was no match in any of the previous cases). The reason is the same. You need a variable for the `case`, but you're not interested in it's actual value.

**Pull request merged**
